linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - gofumpt
    - funlen
    - testpackage
  fast: false

linters-settings:
  wsl:
    allow-cuddle-declarations: true
    force-err-cuddling: true
  gosec:
    excludes:
      - G115
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - n
      - id
    ignore-decls:
      - c echo.Context
      - t testing.T
      - e error
      - i int
      - const C
      - T any
      - m map[string]int
      - w http.ResponseWriter
      - r *http.Request
      - r io.Reader
      - w io.Writer
      - wg *sync.WaitGroup
run:
  timeout: 5m

output:
  sort-results: true